// <auto-generated />
using System;
using DiazFrontDeskApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiazFrontDeskApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230726160709_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiazFrontDeskApp.Models.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageAreaId")
                        .HasColumnType("int");

                    b.Property<int>("PackageStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RetrievedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StoredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PackageId");

                    b.HasIndex("PackageAreaId");

                    b.HasIndex("PackageStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("DiazFrontDeskApp.Models.PackageArea", b =>
                {
                    b.Property<int>("PackageAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageAreaId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("PackageAreaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageAreaId");

                    b.ToTable("PackageAreas");

                    b.HasData(
                        new
                        {
                            PackageAreaId = 1,
                            Capacity = 10,
                            PackageAreaType = "Small"
                        },
                        new
                        {
                            PackageAreaId = 2,
                            Capacity = 5,
                            PackageAreaType = "Medium"
                        },
                        new
                        {
                            PackageAreaId = 3,
                            Capacity = 3,
                            PackageAreaType = "Large"
                        });
                });

            modelBuilder.Entity("DiazFrontDeskApp.Models.PackageStatus", b =>
                {
                    b.Property<int>("PackageStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageStatusId"));

                    b.Property<string>("PackageStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageStatusId");

                    b.ToTable("PackageStatus");

                    b.HasData(
                        new
                        {
                            PackageStatusId = 1,
                            PackageStatusName = "Stored"
                        },
                        new
                        {
                            PackageStatusId = 2,
                            PackageStatusName = "Retrieved"
                        });
                });

            modelBuilder.Entity("DiazFrontDeskApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiazFrontDeskApp.Models.Package", b =>
                {
                    b.HasOne("DiazFrontDeskApp.Models.PackageArea", "PackageArea")
                        .WithMany()
                        .HasForeignKey("PackageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiazFrontDeskApp.Models.PackageStatus", "PackageStatus")
                        .WithMany()
                        .HasForeignKey("PackageStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiazFrontDeskApp.Models.User", "User")
                        .WithMany("Packages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageArea");

                    b.Navigation("PackageStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiazFrontDeskApp.Models.User", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
